// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_request_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_request_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_request_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_request_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_request_2eproto;
namespace PennCloud {
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
}  // namespace PennCloud
PROTOBUF_NAMESPACE_OPEN
template<> ::PennCloud::Request* Arena::CreateMaybeMessage<::PennCloud::Request>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PennCloud {

// ===================================================================

class Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PennCloud.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() override;
  explicit constexpr Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return new Request();
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PennCloud.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kRowkeyFieldNumber = 2,
    kColumnkeyFieldNumber = 3,
    kValue1FieldNumber = 4,
    kValue2FieldNumber = 5,
    kCommandFieldNumber = 6,
    kIsServerFieldNumber = 7,
    kSenderServerIndexFieldNumber = 8,
  };
  // required string type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // optional string rowkey = 2;
  bool has_rowkey() const;
  private:
  bool _internal_has_rowkey() const;
  public:
  void clear_rowkey();
  const std::string& rowkey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rowkey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rowkey();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_rowkey();
  void set_allocated_rowkey(std::string* rowkey);
  private:
  const std::string& _internal_rowkey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rowkey(const std::string& value);
  std::string* _internal_mutable_rowkey();
  public:

  // optional string columnkey = 3;
  bool has_columnkey() const;
  private:
  bool _internal_has_columnkey() const;
  public:
  void clear_columnkey();
  const std::string& columnkey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_columnkey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_columnkey();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_columnkey();
  void set_allocated_columnkey(std::string* columnkey);
  private:
  const std::string& _internal_columnkey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_columnkey(const std::string& value);
  std::string* _internal_mutable_columnkey();
  public:

  // optional bytes value1 = 4;
  bool has_value1() const;
  private:
  bool _internal_has_value1() const;
  public:
  void clear_value1();
  const std::string& value1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value1();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_value1();
  void set_allocated_value1(std::string* value1);
  private:
  const std::string& _internal_value1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value1(const std::string& value);
  std::string* _internal_mutable_value1();
  public:

  // optional bytes value2 = 5;
  bool has_value2() const;
  private:
  bool _internal_has_value2() const;
  public:
  void clear_value2();
  const std::string& value2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value2();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_value2();
  void set_allocated_value2(std::string* value2);
  private:
  const std::string& _internal_value2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value2(const std::string& value);
  std::string* _internal_mutable_value2();
  public:

  // optional string command = 6;
  bool has_command() const;
  private:
  bool _internal_has_command() const;
  public:
  void clear_command();
  const std::string& command() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_command();
  void set_allocated_command(std::string* command);
  private:
  const std::string& _internal_command() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // optional string isServer = 7;
  bool has_isserver() const;
  private:
  bool _internal_has_isserver() const;
  public:
  void clear_isserver();
  const std::string& isserver() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_isserver(ArgT0&& arg0, ArgT... args);
  std::string* mutable_isserver();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_isserver();
  void set_allocated_isserver(std::string* isserver);
  private:
  const std::string& _internal_isserver() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_isserver(const std::string& value);
  std::string* _internal_mutable_isserver();
  public:

  // optional string sender_server_index = 8;
  bool has_sender_server_index() const;
  private:
  bool _internal_has_sender_server_index() const;
  public:
  void clear_sender_server_index();
  const std::string& sender_server_index() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_server_index(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_server_index();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_sender_server_index();
  void set_allocated_sender_server_index(std::string* sender_server_index);
  private:
  const std::string& _internal_sender_server_index() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_server_index(const std::string& value);
  std::string* _internal_mutable_sender_server_index();
  public:

  // @@protoc_insertion_point(class_scope:PennCloud.Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rowkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr columnkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value1_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value2_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr isserver_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_server_index_;
  friend struct ::TableStruct_request_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// required string type = 1;
inline bool Request::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Request::has_type() const {
  return _internal_has_type();
}
inline void Request::clear_type() {
  type_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Request::type() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_type(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.type)
}
inline std::string* Request::mutable_type() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.type)
  return _internal_mutable_type();
}
inline const std::string& Request::_internal_type() const {
  return type_.Get();
}
inline void Request::_internal_set_type(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_type() {
  _has_bits_[0] |= 0x00000001u;
  return type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_type() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.type)
  if (!_internal_has_type()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return type_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.type)
}

// optional string rowkey = 2;
inline bool Request::_internal_has_rowkey() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Request::has_rowkey() const {
  return _internal_has_rowkey();
}
inline void Request::clear_rowkey() {
  rowkey_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Request::rowkey() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.rowkey)
  return _internal_rowkey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_rowkey(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 rowkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.rowkey)
}
inline std::string* Request::mutable_rowkey() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.rowkey)
  return _internal_mutable_rowkey();
}
inline const std::string& Request::_internal_rowkey() const {
  return rowkey_.Get();
}
inline void Request::_internal_set_rowkey(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  rowkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_rowkey() {
  _has_bits_[0] |= 0x00000002u;
  return rowkey_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_rowkey() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.rowkey)
  if (!_internal_has_rowkey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return rowkey_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_rowkey(std::string* rowkey) {
  if (rowkey != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  rowkey_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rowkey,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.rowkey)
}

// optional string columnkey = 3;
inline bool Request::_internal_has_columnkey() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Request::has_columnkey() const {
  return _internal_has_columnkey();
}
inline void Request::clear_columnkey() {
  columnkey_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Request::columnkey() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.columnkey)
  return _internal_columnkey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_columnkey(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 columnkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.columnkey)
}
inline std::string* Request::mutable_columnkey() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.columnkey)
  return _internal_mutable_columnkey();
}
inline const std::string& Request::_internal_columnkey() const {
  return columnkey_.Get();
}
inline void Request::_internal_set_columnkey(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  columnkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_columnkey() {
  _has_bits_[0] |= 0x00000004u;
  return columnkey_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_columnkey() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.columnkey)
  if (!_internal_has_columnkey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return columnkey_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_columnkey(std::string* columnkey) {
  if (columnkey != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  columnkey_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), columnkey,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.columnkey)
}

// optional bytes value1 = 4;
inline bool Request::_internal_has_value1() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Request::has_value1() const {
  return _internal_has_value1();
}
inline void Request::clear_value1() {
  value1_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Request::value1() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.value1)
  return _internal_value1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_value1(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 value1_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.value1)
}
inline std::string* Request::mutable_value1() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.value1)
  return _internal_mutable_value1();
}
inline const std::string& Request::_internal_value1() const {
  return value1_.Get();
}
inline void Request::_internal_set_value1(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  value1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_value1() {
  _has_bits_[0] |= 0x00000008u;
  return value1_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_value1() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.value1)
  if (!_internal_has_value1()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return value1_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_value1(std::string* value1) {
  if (value1 != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  value1_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value1,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.value1)
}

// optional bytes value2 = 5;
inline bool Request::_internal_has_value2() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Request::has_value2() const {
  return _internal_has_value2();
}
inline void Request::clear_value2() {
  value2_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& Request::value2() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.value2)
  return _internal_value2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_value2(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000010u;
 value2_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.value2)
}
inline std::string* Request::mutable_value2() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.value2)
  return _internal_mutable_value2();
}
inline const std::string& Request::_internal_value2() const {
  return value2_.Get();
}
inline void Request::_internal_set_value2(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  value2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_value2() {
  _has_bits_[0] |= 0x00000010u;
  return value2_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_value2() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.value2)
  if (!_internal_has_value2()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return value2_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_value2(std::string* value2) {
  if (value2 != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  value2_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value2,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.value2)
}

// optional string command = 6;
inline bool Request::_internal_has_command() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Request::has_command() const {
  return _internal_has_command();
}
inline void Request::clear_command() {
  command_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& Request::command() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.command)
  return _internal_command();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_command(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000020u;
 command_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.command)
}
inline std::string* Request::mutable_command() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.command)
  return _internal_mutable_command();
}
inline const std::string& Request::_internal_command() const {
  return command_.Get();
}
inline void Request::_internal_set_command(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  command_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_command() {
  _has_bits_[0] |= 0x00000020u;
  return command_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_command() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.command)
  if (!_internal_has_command()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return command_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  command_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), command,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.command)
}

// optional string isServer = 7;
inline bool Request::_internal_has_isserver() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Request::has_isserver() const {
  return _internal_has_isserver();
}
inline void Request::clear_isserver() {
  isserver_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& Request::isserver() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.isServer)
  return _internal_isserver();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_isserver(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000040u;
 isserver_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.isServer)
}
inline std::string* Request::mutable_isserver() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.isServer)
  return _internal_mutable_isserver();
}
inline const std::string& Request::_internal_isserver() const {
  return isserver_.Get();
}
inline void Request::_internal_set_isserver(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  isserver_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_isserver() {
  _has_bits_[0] |= 0x00000040u;
  return isserver_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_isserver() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.isServer)
  if (!_internal_has_isserver()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  return isserver_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_isserver(std::string* isserver) {
  if (isserver != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  isserver_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), isserver,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.isServer)
}

// optional string sender_server_index = 8;
inline bool Request::_internal_has_sender_server_index() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Request::has_sender_server_index() const {
  return _internal_has_sender_server_index();
}
inline void Request::clear_sender_server_index() {
  sender_server_index_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000080u;
}
inline const std::string& Request::sender_server_index() const {
  // @@protoc_insertion_point(field_get:PennCloud.Request.sender_server_index)
  return _internal_sender_server_index();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Request::set_sender_server_index(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000080u;
 sender_server_index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PennCloud.Request.sender_server_index)
}
inline std::string* Request::mutable_sender_server_index() {
  // @@protoc_insertion_point(field_mutable:PennCloud.Request.sender_server_index)
  return _internal_mutable_sender_server_index();
}
inline const std::string& Request::_internal_sender_server_index() const {
  return sender_server_index_.Get();
}
inline void Request::_internal_set_sender_server_index(const std::string& value) {
  _has_bits_[0] |= 0x00000080u;
  sender_server_index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Request::_internal_mutable_sender_server_index() {
  _has_bits_[0] |= 0x00000080u;
  return sender_server_index_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Request::release_sender_server_index() {
  // @@protoc_insertion_point(field_release:PennCloud.Request.sender_server_index)
  if (!_internal_has_sender_server_index()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000080u;
  return sender_server_index_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Request::set_allocated_sender_server_index(std::string* sender_server_index) {
  if (sender_server_index != nullptr) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  sender_server_index_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sender_server_index,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PennCloud.Request.sender_server_index)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PennCloud

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_request_2eproto
